server:
  port: 8093
  
spring:
  application:
    name: tss-zipkin-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
      
logging:
  level:
    root: INFO
    com.tss: DEBUG
